
name: Publish
 
on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'
 
permissions:
  contents: write
  id-token: write
  pull-requests: write
 
jobs:
  publish:
    name: Publish to pub.dev
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1